# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b4adf2ef665c82d878cba4275751a2ee629e038ae528209e2eb2d9603ca2fbb77bc756e4ad9bad6766203409f4575fe2a7c61853c83b9d3f62c24181ffea32f

test:
  secret_key_base: 2398245881a955addf75839a9bd8bede8d691889b96db01e0d5c5a945cd7991fc481e368188db34e336cfb87363f8e20d525d187a4e84ba26001e737151b69df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
